[book]
title = "یادگیری Nginx"
authors = ["learn-nginx"]
language = "fa"
text-direction = "rtl"
src = "src"

[build]
build-dir = "book"
create-missing = false

[output.html]
default-theme = "rust"
preferred-dark-theme = "navy"
smart-punctuation = true
additional-css = ["theme/custom.css"]
no-section-label = true
site-url = "/learn-nginx/"
git-repository-url = "https://github.com/yasersharifi/learn-nginx"

[output.html.search]
enable = true
limit-results = 30

[output.html.print]
enable = true
