import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
	docsSidebar: [
		"introduction",
		"daily-guide",
		"review",
		{
			type: "category",
			label: "Nginx",
			link: { type: "doc", id: "nginx/index" },
			items: [{ type: "autogenerated", dirName: "nginx" }],
		},
		{
			type: "category",
			label: "Linux",
			link: { type: "doc", id: "linux/index" },
			items: [{ type: "autogenerated", dirName: "linux" }],
		},
		{
			type: "category",
			label: "Git",
			link: { type: "doc", id: "git/index" },
			items: [{ type: "autogenerated", dirName: "git" }],
		},
		{
			type: "category",
			label: "مرجع دستورات",
			link: { type: "doc", id: "commands/index" },
			items: [{ type: "autogenerated", dirName: "commands" }],
		},
	],
};

export default sidebars;
