import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'introduction',
    'review',
    {
      type: 'category',
      label: 'Nginx',
      link: {type: 'doc', id: 'nginx/index'},
      items: [{type: 'autogenerated', dirName: 'nginx'}],
    },
    {
      type: 'category',
      label: 'Linux',
      link: {type: 'doc', id: 'linux/index'},
      items: [{type: 'autogenerated', dirName: 'linux'}],
    },
    {
      type: 'category',
      label: 'Git',
      link: {type: 'doc', id: 'git/index'},
      items: [{type: 'autogenerated', dirName: 'git'}],
    },
  ],
};

export default sidebars;
